import { Geist, Geist_Mono, Parkinsans, Poppins, REM } from "next/font/google";
import "./globals.css";

import NavbarWrapper from "./user/components/NavbarWrapper";
import FooterWrapper from "./user/components/FooterWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});




const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  variable: "--font-poppins",
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  ${poppins.variable} h-full antialiased`}
    >
      
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <div className="bg-[#FFFAEB]">  <NavbarWrapper/></div>
      
        
         <main className="">
          {children}
        </main>

         <div className="bg-[#FFFAEB]">
         <FooterWrapper />
         </div>
        </body>
    </html>
  );
}
